" Vimrc By Talented Unicorn 
" --------------------------

" Set terminal color to 256 color mode
set t_Co=256

" Set large history size
set history=700

" Edit
set number		" Set line number on
set showmatch		" Highlight matching brace
set visualbell		" Use visual bell (no beeping)
set autoindent		" Auto-indent new lines
set smartindent		" Enable smart-indent
set shiftwidth=4	" Auto indent spaces
set tabstop=4		" Number of spaces per tab
set wrap			" Wrap lines
set smarttab		" Enable smart-tab
set autoread		" Auto read when file is changed from outside
set foldenable		" Enable code folding
set foldmethod=indent	" Fold code by indent
set relativenumber	" Show relative number

" Turn backup off, since most stuff is in SVN, git et.c anyway...
set nobackup
set nowb
set noswapfile

" Delete trailing white space on save, useful for Python and CoffeeScript ;)
func! DeleteTrailingWS()
  exe "normal mz"
  %s/\s\+$//ge
  exe "normal `z"
endfunc
autocmd BufWrite *.py :call DeleteTrailingWS()
autocmd BufWrite *.coffee :call DeleteTrailingWS()

" Key binding
map <F3> :Explore<cr> " Show Explore
let mapleader = "`"
nmap <leader>w :w!<cr>	" Fast saving

" Navigation
" - Buffers
nmap <F1> :bp!<cr>	" Previous buffer
nmap <F2> :bn!<cr>	" Next buffer
map <silent> <leader><delete> :bd<cr>	" Delete buffer - leader+dd
map <silent> <leader>n :enew<cr>	" Create empty buffer in current window
" Press leader and space to remove highlights
map <silent> <leader><space> :noh<cr>	

" Smart way to move between windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" Search
set hlsearch		" Highlight search results
set smartcase		" Enable smart-case search
set ignorecase		" Ignore case in search ALWAYS
nmap <silent> <leader>/ :nohlsearch<cr>	" Remove search highlights

set modifiable		" enable modifiable

" UI
set wildmenu		" Wild menu is on
set showmatch		" Matching brackets yeah?
set showcmd			" Show command on UI

" - Syntax highlighting
syntax enable
try
	colorscheme desert
catch
endtry

" set cshtml files to html syntax 
au BufNewFile,BufRead *.cshtml set filetype=html

" - vim-airline
set laststatus=2
let g:airline#extensions#tabline#enabled = 1	" Automatically display buffers when there's only one tab open
let g:airline_powerline_fonts = 1	" Set powerline fonts
let g:airline_theme = "bubblegum"	" Set airline theme
let g:airline#extensions#branch#enabled = 1	" Enable display of current branch

" - CtrlP
let g:ctrlp_custom_ignore = {
	\'dir':  '\v[\/](\.(git|hg|svn)|\Debug|\Release|node_modules|bower_components)$',
	\'file': '\v\.(exe|so|dll|class|png|jpg|jpeg|map)$',
\}

let g:ctrlp_working_path_mode = 'r'

let g:ctrlp_cmd = 'CtrlPMixed'

" faster search with ag
let g:ctrlp_user_command = 'ag %s -i --nocolor --nogroup --hidden
      \ --ignore .git
      \ --ignore .svn
      \ --ignore .hg
      \ --ignore .DS_Store
      \ --ignore "**/*.pyc"
      \ -g ""'

" When you press gv you Ag after the selected text
vnoremap <silent> gv :call VisualSelection('gv', '')<CR>

" Select and replace
vnoremap <silent> <leader>r :call VisualSelection('replace', '')<CR>

" Visual mode pressing * or # searches for the current selection
" Super useful! From an idea by Michael Naumann
vnoremap <silent> * :call VisualSelection('f', '')<CR>
vnoremap <silent> # :call VisualSelection('b', '')<CR>

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Helper functions
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
function! CmdLine(str)
    exe "menu Foo.Bar :" . a:str
    emenu Foo.Bar
    unmenu Foo
endfunction 

function! VisualSelection(direction, extra_filter) range
    let l:saved_reg = @"
    execute "normal! vgvy"

    let l:pattern = escape(@", '\\/.*$^~[]')
    let l:pattern = substitute(l:pattern, "\n$", "", "")

    if a:direction == 'b'
        execute "normal ?" . l:pattern . "^M"
    elseif a:direction == 'gv'
        call CmdLine("Ag \"" . l:pattern . "\" " )
    elseif a:direction == 'replace'
        call CmdLine("%s" . '/'. l:pattern . '/')
    elseif a:direction == 'f'
        execute "normal /" . l:pattern . "^M"
    endif

    let @/ = l:pattern
    let @" = l:saved_reg
endfunction


" Vundle - Vim plugin manager
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Managed packages
Plugin 'gmarik/Vundle.vim'

Plugin 'cakebaker/scss-syntax.vim'
Plugin 'othree/html5.vim'
Plugin 'jelera/vim-javascript-syntax'
Plugin 'bling/vim-airline'
Plugin 'mattn/emmet-vim'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'tpope/vim-commentary'
call vundle#end()
