" Vimrc By Talented Unicorn 
" --------------------------

" Set terminal color to 256 color mode
set t_Co=256

" Edit
set number		" Set line number on
set showmatch		" Highlight matching brace
set visualbell		" Use visual bell (no beeping)
set autoindent		" Auto-indent new lines
set smartindent		" Enable smart-indent
set shiftwidth=4	" Auto indent spaces
set tabstop=4		" Number of spaces per tab
set wrap			" Wrap lines
set smarttab		" Enable smart-tab
set autoread		" Auto read when file is changed from outside
set foldenable		" Enable code folding
set foldmethod=manual	" Fold code manually
set relativenumber	" Show relative number

" Turn backup off, since most stuff is in SVN, git et.c anyway...
set nobackup
set nowb
set noswapfile

" Key binding
map <F3> :NERDTreeToggle<CR>	" Toggle NERDTree menu
let mapleader = "`"
nmap <leader>w :w!<cr>	" Fast saving

" Navigation
" - Buffers
nmap <F4> :bp<cr>	" Previous buffer
nmap <F5> :bn<cr>	" Next buffer
map <silent> <leader><cr> :noh<cr>	" Press leader and enter to remove highlights

" Smart way to move between windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" Search
set hlsearch		" Highlight search results
set smartcase		" Enable smart-case search
set ignorecase		" Ignore case in search ALWAYS

set modifiable		" enable modifiable

" UI
set wildmenu		" Wild menu is on
set showmatch		" Matching brackets yeah?
set showcmd			" Show command on UI

" - Syntax highlighting
syntax enable
try
	colorscheme desert
catch
endtry
set background=dark

" set cshtml files to html syntax 
au BufNewFile,BufRead *.cshtml set filetype=html

" - vim-airline
set laststatus=2
let g:airline#extensions#tabline#enabled = 1	" Automatically display buffers when there's only one tab open
let g:airline_powerline_fonts = 1	" Set powerline fonts
let g:airline_theme = "bubblegum"	" Set airline theme

" Vundle - Vim plugin manager
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Managed packages
Plugin 'gmarik/Vundle.vim'

Plugin 'scrooloose/nerdtree'
Plugin 'cakebaker/scss-syntax.vim'
Plugin 'othree/html5.vim'
Plugin 'jelera/vim-javascript-syntax'
Plugin 'bling/vim-airline'
Plugin 'mattn/emmet-vim'
Plugin 'ctrlpvim/ctrlp.vim'
call vundle#end()
