# Aliases
# Shortcuts
#alias ..='cd ../'
#alias ..2='cd ../../'
#alias ..3='cd ../../../'
#alias ..4='cd ../../../../'
#alias g='git'
#alias got='git pull'
#alias gitprompt='. $HOME/MyDots/Linux-Configs/git_prompt'

# Package Management

alias installpkg='sudo apt-get install'
alias removepkg='sudo apt-get remove'
alias repoupdate='sudo apt-get update'
alias findpkg='apt-cache search'
alias sysupdate='repoupdate && sudo apt-get upgrade'
alias addrepo='sudo add-apt-repository' 

# ubuntu fix for sudo and PATH
# alias sudo='sudo env PATH=$PATH'

# Composer
alias composer='$HOME/bin/composer.phar'

# Deployer
alias deployer='$HOME/bin/deployer.phar'
alias dep='$HOME/bin/deployer.phar'

# Git-FTP
alias ftpDeploy='git-ftp push'

# Tmux 
alias tm='tmux -2 new -s home -n process'

# Docker
alias dockerStart='docker-compose start'
alias dockerStop='docker-compose stop'
alias dockerRestart='docker-compose restart'

# Bluetooth fix
alias bluetoothload='sudo pactl load-module module-bluetooth-discover'
alias dropboxStart='dropbox stop && env XDG_CURRENT_DESKTOP=Unity QT_STYLE_OVERRIDE='' dropbox start'

# Weather
alias weather='curl wttr.in'

# Clipboard tool
alias pbcopy='xsel --clipboard --input'  # - copy to clipboard
alias pbpaste='xsel --clipboard --output'  # - paste from clipboard
