# Aliases
# Shortcuts
#alias ..='cd ../'
#alias ..2='cd ../../'
#alias ..3='cd ../../../'
#alias ..4='cd ../../../../'
#alias g='git'
#alias got='git pull'
#alias gitprompt='. $HOME/MyDots/Linux-Configs/git_prompt'

# Package Management

alias installpkg='sudo apt-get install'
alias removepkg='sudo apt-get remove'
alias repoupdate='sudo apt-get update'
alias findpkg='apt-cache search'
alias sysupdate='repoupdate && sudo apt-get upgrade'
alias addrepo='sudo add-apt-repository' 

# ubuntu fix for sudo and PATH
# alias sudo='sudo env PATH=$PATH'

# Composer
alias composer='$HOME/bin/composer.phar'

# Tmux 
alias tm='tmux new -s estorm -n process'

# Bluetooth fix
alias bluetoothload='sudo pactl load-module module-bluetooth-discover'
