# Aliases
# Package Management

alias installpkg='sudo apt-get install'
alias removepkg='sudo apt-get remove'
alias repoupdate='sudo apt-get update'
alias findpkg='apt-cache search'
alias sysupdate='repoupdate && sudo apt-get upgrade'
alias addrepo='sudo add-apt-repository' 

# ubuntu fix for sudo and PATH
# alias sudo='sudo env PATH=$PATH'

# LAMPP
#alias webserverstart='sudo lampp start'
#alias webserverstop='sudo lampp stop'
alias webservercontrol='sudo manager-linux-x64.run'
alias webroot='cd /opt/lampp/htdocs'
alias startapache='sudo lampp startapache'
alias stopapache='sudo lampp stopapache'
alias restartapache='sudo lampp restartapache'
alias startmysql='sudo lampp startmysql'
alias stopmysql='sudo lampp stopmysql'
alias restartmysql='sudo lampp restartmysql'
